name: Build and test Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goVer: ["1.17", "1.18", "1.19"]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goVer }}
          check-latest: true
          cache: true

      - name: Unit
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...

      - name: Staticcheck
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goVer: ["1.17", "1.18", "1.19"]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goVer }}
          check-latest: true
          cache: true

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build ./cmd

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}