name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ["1.17", "1.18", "1.19"]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goVer }}
          check-latest: true
          # cache: true

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Unit test
        # env:
        #   GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...

      # - name: Staticcheck
      #   # env:
      #   #   GOPROXY: "https://proxy.golang.org"
      #   run: |
      #     export PATH=${PATH}:`go env GOPATH`/bin
      #     go get -u honnef.co/go/tools/cmd/staticcheck
      #     staticcheck ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}